version: "3.9"
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - arquitectura-software
    volumes:
      - ./sql/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
  todo:
    image: todo:1.0.3
    ports:
      - ${TODO_PORT}:8080
    networks:
      - arquitectura-software
    volumes:
      - /opt/arqui_software/logs:/opt/arqui_software/logs
    environment:
      - IP=${IP}
    depends_on:
      - mysql

networks:
  arquitectura-software: