spring:
  datasource:
    url: jdbc:mysql://${IP:localhost}:${PORT:3306}/${DATABASE_NAME:test}
    username: ${USERNAME:root}
    password: ${PASSWORD:asdjkkqw}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: todo

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 5
          max-interval: 10s
          multiplier: 2

server:
  port: 8080
