spring:
  datasource:
    url: jdbc:mysql://${IP:localhost}:${PORT:3306}/${DATABASE_NAME:test}
    username: ${USERNAME:root}
    password: ${PASSWORD:my-secret-pw}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: todo

server:
  port: 8080
